apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kfkk4ntbu-python 
  janus-idp.io/tekton: kfkk4ntbu-python
  backstage.io/kubernetes-id: kfkk4ntbu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kfkk4ntbu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  